name: Publish to GitHub Package Registry
on:
  release:
    types: [created]

jobs:
  publish_gqr:
    name: Publish to github registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - run: . .github/workflows/gpr_add_scope.sh
      - run: npm install
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
